insert into productos (nombre, descripcion, precio, existencias) values ('Wine - Prosecco Valdobiaddene', 'Books', 11769, 50);
insert into productos (nombre, descripcion, precio, existencias) values ('Duck - Whole', 'Toys', 8661, 36);
insert into productos (nombre, descripcion, precio, existencias) values ('Zucchini - Mini, Green', 'Kids', 2578, 62);
insert into productos (nombre, descripcion, precio, existencias) values ('Foil Wrap', 'Clothing', 6253, 30);
insert into productos (nombre, descripcion, precio, existencias) values ('Wine - Shiraz South Eastern', 'Games', 16078, 77);
insert into productos (nombre, descripcion, precio, existencias) values ('Vinegar - Raspberry', 'Industrial', 16922, 79);
insert into productos (nombre, descripcion, precio, existencias) values ('Crab - Dungeness, Whole', 'Movies', 12938, 60);
insert into productos (nombre, descripcion, precio, existencias) values ('Coconut - Shredded, Sweet', 'Industrial', 7899, 69);
insert into productos (nombre, descripcion, precio, existencias) values ('Cheese - Brick With Onion', 'Electronics', 18141, 63);
insert into productos (nombre, descripcion, precio, existencias) values ('Herb Du Provence - Primerba', 'Grocery', 14737, 25);
insert into productos (nombre, descripcion, precio, existencias) values ('Wine - Magnotta - Cab Franc', 'Kids', 14925, 40);
insert into productos (nombre, descripcion, precio, existencias) values ('Salt - Sea', 'Books', 6838, 2);
insert into productos (nombre, descripcion, precio, existencias) values ('Wine - Magnotta - Pinot Gris Sr', 'Baby', 11901, 34);
insert into productos (nombre, descripcion, precio, existencias) values ('Mousse - Mango', 'Baby', 911, 75);
insert into productos (nombre, descripcion, precio, existencias) values ('Beans - Butter Lrg Lima', 'Computers', 6838, 20);
insert into productos (nombre, descripcion, precio, existencias) values ('Almonds Ground Blanched', 'Home', 19207, 51);
insert into productos (nombre, descripcion, precio, existencias) values ('Vinegar - Cider', 'Books', 14917, 26);
insert into productos (nombre, descripcion, precio, existencias) values ('Egg Patty Fried', 'Electronics', 17514, 32);
insert into productos (nombre, descripcion, precio, existencias) values ('Pepsi - 600ml', 'Computers', 17729, 12);
insert into productos (nombre, descripcion, precio, existencias) values ('Pie Shell - 9', 'Automotive', 11442, 45);
insert into productos (nombre, descripcion, precio, existencias) values ('Chicken - Ground', 'Health', 4436, 7);
insert into productos (nombre, descripcion, precio, existencias) values ('Beer - Sleeman Fine Porter', 'Games', 19033, 31);
insert into productos (nombre, descripcion, precio, existencias) values ('Bagels Poppyseed', 'Industrial', 3229, 42);
insert into productos (nombre, descripcion, precio, existencias) values ('Bread - Italian Corn Meal Poly', 'Electronics', 19463, 6);
insert into productos (nombre, descripcion, precio, existencias) values ('Carbonated Water - Orange', 'Electronics', 14477, 84);
insert into productos (nombre, descripcion, precio, existencias) values ('Wine - Periguita Fonseca', 'Outdoors', 18886, 73);
insert into productos (nombre, descripcion, precio, existencias) values ('Flower - Carnations', 'Industrial', 15447, 52);
insert into productos (nombre, descripcion, precio, existencias) values ('Beer - Maudite', 'Health', 14348, 60);
insert into productos (nombre, descripcion, precio, existencias) values ('Arrowroot', 'Electronics', 16412, 41);
insert into productos (nombre, descripcion, precio, existencias) values ('Pastry - Banana Tea Loaf', 'Shoes', 10295, 51);
insert into productos (nombre, descripcion, precio, existencias) values ('Cocoa Powder - Natural', 'Beauty', 1811, 26);
insert into productos (nombre, descripcion, precio, existencias) values ('Cheese - Grie Des Champ', 'Home', 7259, 21);
insert into productos (nombre, descripcion, precio, existencias) values ('Cleaner - Pine Sol', 'Computers', 4436, 73);
insert into productos (nombre, descripcion, precio, existencias) values ('Steampan - Lid For Half Size', 'Baby', 1898, 99);
insert into productos (nombre, descripcion, precio, existencias) values ('Beer - Heinekin', 'Computers', 19921, 31);
insert into productos (nombre, descripcion, precio, existencias) values ('Kale - Red', 'Computers', 8289, 19);
insert into productos (nombre, descripcion, precio, existencias) values ('Veal - Nuckle', 'Automotive', 19874, 3);
insert into productos (nombre, descripcion, precio, existencias) values ('Vodka - Lemon, Absolut', 'Music', 12740, 32);
insert into productos (nombre, descripcion, precio, existencias) values ('Wine - Bourgogne 2002, La', 'Books', 13706, 17);
insert into productos (nombre, descripcion, precio, existencias) values ('Wine - Red, Cabernet Merlot', 'Clothing', 5484, 30);
insert into productos (nombre, descripcion, precio, existencias) values ('Flavouring - Rum', 'Sports', 13042, 58);
insert into productos (nombre, descripcion, precio, existencias) values ('Tea - English Breakfast', 'Shoes', 19029, 27);
insert into productos (nombre, descripcion, precio, existencias) values ('Ice Cream Bar - Oreo Cone', 'Shoes', 5132, 16);
insert into productos (nombre, descripcion, precio, existencias) values ('Pears - Fiorelle', 'Sports', 12188, 89);
insert into productos (nombre, descripcion, precio, existencias) values ('Lotus Rootlets - Canned', 'Music', 201, 44);
insert into productos (nombre, descripcion, precio, existencias) values ('Higashimaru Usukuchi Soy', 'Toys', 12832, 8);
insert into productos (nombre, descripcion, precio, existencias) values ('Extract - Lemon', 'Tools', 6800, 52);
insert into productos (nombre, descripcion, precio, existencias) values ('Appetizer - Mini Egg Roll, Shrimp', 'Books', 9449, 49);
insert into productos (nombre, descripcion, precio, existencias) values ('Truffle Cups Green', 'Shoes', 13720, 3);
insert into productos (nombre, descripcion, precio, existencias) values ('Flour - Bran, Red', 'Health', 8409, 39);
insert into productos (nombre, descripcion, precio, existencias) values ('Vinegar - Sherry', 'Health', 9480, 84);
insert into productos (nombre, descripcion, precio, existencias) values ('Onions - Red', 'Movies', 8946, 99);
insert into productos (nombre, descripcion, precio, existencias) values ('Limes', 'Baby', 519, 93);
insert into productos (nombre, descripcion, precio, existencias) values ('Beer - Blue Light', 'Shoes', 15618, 96);
insert into productos (nombre, descripcion, precio, existencias) values ('Venison - Racks Frenched', 'Home', 15762, 37);
insert into productos (nombre, descripcion, precio, existencias) values ('Potatoes - Parissienne', 'Garden', 10106, 46);
insert into productos (nombre, descripcion, precio, existencias) values ('Energy - Boo - Koo', 'Industrial', 19603, 19);
insert into productos (nombre, descripcion, precio, existencias) values ('Gloves - Goldtouch Disposable', 'Electronics', 6324, 27);
insert into productos (nombre, descripcion, precio, existencias) values ('Beans - Fava Fresh', 'Health', 5339, 88);
insert into productos (nombre, descripcion, precio, existencias) values ('Cookie - Oreo 100x2', 'Music', 4479, 84);
insert into productos (nombre, descripcion, precio, existencias) values ('Oil - Cooking Spray', 'Home', 2071, 25);
insert into productos (nombre, descripcion, precio, existencias) values ('Wine - Tio Pepe Sherry Fino', 'Outdoors', 5673, 12);
insert into productos (nombre, descripcion, precio, existencias) values ('Coffee Beans - Chocolate', 'Garden', 15957, 21);
insert into productos (nombre, descripcion, precio, existencias) values ('Island Oasis - Banana Daiquiri', 'Beauty', 19214, 18);
insert into productos (nombre, descripcion, precio, existencias) values ('Tomato - Tricolor Cherry', 'Tools', 15431, 11);
insert into productos (nombre, descripcion, precio, existencias) values ('Mushroom - Porcini, Dry', 'Home', 1377, 57);
insert into productos (nombre, descripcion, precio, existencias) values ('Towel Multifold', 'Outdoors', 262, 34);
insert into productos (nombre, descripcion, precio, existencias) values ('Chicken - Whole Roasting', 'Industrial', 50, 65);
insert into productos (nombre, descripcion, precio, existencias) values ('Transfer Sheets', 'Toys', 5844, 36);
insert into productos (nombre, descripcion, precio, existencias) values ('Flower - Leather Leaf Fern', 'Industrial', 10210, 72);
insert into productos (nombre, descripcion, precio, existencias) values ('Vodka - Moskovskaya', 'Grocery', 2120, 63);
insert into productos (nombre, descripcion, precio, existencias) values ('Pear - Prickly', 'Movies', 18654, 73);
insert into productos (nombre, descripcion, precio, existencias) values ('Amarula Cream', 'Movies', 19212, 45);
insert into productos (nombre, descripcion, precio, existencias) values ('Pheasants - Whole', 'Movies', 1816, 10);
insert into productos (nombre, descripcion, precio, existencias) values ('Cheese - Bocconcini', 'Sports', 18513, 13);
insert into productos (nombre, descripcion, precio, existencias) values ('Wine - Cahors Ac 2000, Clos', 'Computers', 10762, 82);
insert into productos (nombre, descripcion, precio, existencias) values ('Marsala - Sperone, Fine, D.o.c.', 'Outdoors', 17862, 100);
insert into productos (nombre, descripcion, precio, existencias) values ('Pork - Chop, Frenched', 'Tools', 15298, 37);
insert into productos (nombre, descripcion, precio, existencias) values ('Skewers - Bamboo', 'Music', 10006, 83);
insert into productos (nombre, descripcion, precio, existencias) values ('Buttons', 'Beauty', 7104, 67);
insert into productos (nombre, descripcion, precio, existencias) values ('Uniform Linen Charge', 'Sports', 9329, 72);
insert into productos (nombre, descripcion, precio, existencias) values ('Bacardi Limon', 'Sports', 14671, 39);
insert into productos (nombre, descripcion, precio, existencias) values ('Wine - Merlot Vina Carmen', 'Baby', 3833, 63);
insert into productos (nombre, descripcion, precio, existencias) values ('Strawberries - California', 'Outdoors', 1062, 83);
insert into productos (nombre, descripcion, precio, existencias) values ('Sauce - Balsamic Viniagrette', 'Shoes', 6934, 26);
insert into productos (nombre, descripcion, precio, existencias) values ('Beets - Golden', 'Games', 19448, 75);
insert into productos (nombre, descripcion, precio, existencias) values ('Ice Cream Bar - Rolo Cone', 'Garden', 323, 32);
insert into productos (nombre, descripcion, precio, existencias) values ('Pepper - Orange', 'Tools', 1474, 77);
insert into productos (nombre, descripcion, precio, existencias) values ('Shrimp - Tiger 21/25', 'Beauty', 13138, 24);
insert into productos (nombre, descripcion, precio, existencias) values ('Turkey - Breast, Bone - In', 'Automotive', 19594, 19);
insert into productos (nombre, descripcion, precio, existencias) values ('Tuna - Canned, Flaked, Light', 'Movies', 3044, 96);
insert into productos (nombre, descripcion, precio, existencias) values ('Beer - Pilsner Urquell', 'Beauty', 12971, 13);
insert into productos (nombre, descripcion, precio, existencias) values ('Creme De Menthe Green', 'Tools', 8187, 41);
insert into productos (nombre, descripcion, precio, existencias) values ('Squid U5 - Thailand', 'Books', 8202, 30);
insert into productos (nombre, descripcion, precio, existencias) values ('Bols Melon Liqueur', 'Kids', 10986, 22);
insert into productos (nombre, descripcion, precio, existencias) values ('Rabbit - Saddles', 'Computers', 13469, 66);
insert into productos (nombre, descripcion, precio, existencias) values ('Apricots - Dried', 'Health', 8715, 43);
insert into productos (nombre, descripcion, precio, existencias) values ('Mushroom - King Eryingii', 'Automotive', 8271, 77);
insert into productos (nombre, descripcion, precio, existencias) values ('Muffin Mix - Morning Glory', 'Games', 10993, 72);
insert into productos (nombre, descripcion, precio, existencias) values ('Puree - Strawberry', 'Outdoors', 11209, 60);
insert into productos (nombre, descripcion, precio, existencias) values ('Seedlings - Mix, Organic', 'Games', 5102, 73);
insert into productos (nombre, descripcion, precio, existencias) values ('Leeks - Baby, White', 'Outdoors', 4354, 44);
insert into productos (nombre, descripcion, precio, existencias) values ('Sauce Bbq Smokey', 'Home', 5263, 15);
insert into productos (nombre, descripcion, precio, existencias) values ('Lotus Rootlets - Canned', 'Tools', 7595, 87);
insert into productos (nombre, descripcion, precio, existencias) values ('Food Colouring - Blue', 'Home', 10074, 80);
insert into productos (nombre, descripcion, precio, existencias) values ('Carbonated Water - Lemon Lime', 'Industrial', 4174, 86);
insert into productos (nombre, descripcion, precio, existencias) values ('Bread - White, Unsliced', 'Beauty', 7726, 78);
insert into productos (nombre, descripcion, precio, existencias) values ('Nut - Pine Nuts, Whole', 'Kids', 11442, 8);
insert into productos (nombre, descripcion, precio, existencias) values ('Sproutsmustard Cress', 'Books', 1671, 83);
insert into productos (nombre, descripcion, precio, existencias) values ('Veal - Inside', 'Health', 9606, 46);
insert into productos (nombre, descripcion, precio, existencias) values ('Nantuket Peach Orange', 'Games', 5212, 36);
insert into productos (nombre, descripcion, precio, existencias) values ('Cookies Oatmeal Raisin', 'Movies', 8737, 7);
insert into productos (nombre, descripcion, precio, existencias) values ('Energy Drink - Franks Original', 'Electronics', 14565, 60);
insert into productos (nombre, descripcion, precio, existencias) values ('Venison - Racks Frenched', 'Games', 8083, 36);
insert into productos (nombre, descripcion, precio, existencias) values ('Baking Powder', 'Automotive', 10565, 34);
insert into productos (nombre, descripcion, precio, existencias) values ('Ginger - Crystalized', 'Industrial', 18746, 47);
insert into productos (nombre, descripcion, precio, existencias) values ('Sobe - Berry Energy', 'Health', 7631, 89);
insert into productos (nombre, descripcion, precio, existencias) values ('Tea - Mint', 'Sports', 1118, 49);
insert into productos (nombre, descripcion, precio, existencias) values ('Absolut Citron', 'Outdoors', 4883, 72);
insert into productos (nombre, descripcion, precio, existencias) values ('Wine - Casillero Del Diablo', 'Health', 12544, 8);
insert into productos (nombre, descripcion, precio, existencias) values ('Beer - True North Strong Ale', 'Baby', 6224, 6);
insert into productos (nombre, descripcion, precio, existencias) values ('Wine - White, Antinore Orvieto', 'Tools', 17548, 20);
insert into productos (nombre, descripcion, precio, existencias) values ('Tart Shells - Savory, 3', 'Shoes', 822, 47);
insert into productos (nombre, descripcion, precio, existencias) values ('Chicken - Wieners', 'Beauty', 7308, 73);
insert into productos (nombre, descripcion, precio, existencias) values ('Wine - Vouvray Cuvee Domaine', 'Automotive', 9123, 79);
insert into productos (nombre, descripcion, precio, existencias) values ('Apricots Fresh', 'Movies', 17610, 37);
insert into productos (nombre, descripcion, precio, existencias) values ('Bread - Rosemary Focaccia', 'Movies', 2574, 67);
insert into productos (nombre, descripcion, precio, existencias) values ('Squash - Guords', 'Grocery', 13457, 80);
insert into productos (nombre, descripcion, precio, existencias) values ('Tea - Honey Green Tea', 'Automotive', 7845, 48);
insert into productos (nombre, descripcion, precio, existencias) values ('Chick Peas - Canned', 'Kids', 10889, 7);
insert into productos (nombre, descripcion, precio, existencias) values ('Eggplant Oriental', 'Clothing', 2843, 89);
insert into productos (nombre, descripcion, precio, existencias) values ('Spring Roll Wrappers', 'Industrial', 17714, 62);
insert into productos (nombre, descripcion, precio, existencias) values ('Wine - Mondavi Coastal Private', 'Industrial', 15956, 26);
insert into productos (nombre, descripcion, precio, existencias) values ('Butter - Salted', 'Books', 7554, 57);
insert into productos (nombre, descripcion, precio, existencias) values ('Sambuca Cream', 'Grocery', 4215, 7);
insert into productos (nombre, descripcion, precio, existencias) values ('Juice - Grapefruit, 341 Ml', 'Clothing', 4965, 96);
insert into productos (nombre, descripcion, precio, existencias) values ('Creme De Cacao White', 'Movies', 15087, 52);
insert into productos (nombre, descripcion, precio, existencias) values ('Wine - Harrow Estates, Vidal', 'Music', 8830, 87);
insert into productos (nombre, descripcion, precio, existencias) values ('Sour Puss - Tangerine', 'Health', 16982, 59);
insert into productos (nombre, descripcion, precio, existencias) values ('Nut - Hazelnut, Ground, Natural', 'Sports', 1042, 5);
insert into productos (nombre, descripcion, precio, existencias) values ('Oil - Avocado', 'Automotive', 15134, 88);
insert into productos (nombre, descripcion, precio, existencias) values ('Chicken - White Meat, No Tender', 'Beauty', 15551, 8);
insert into productos (nombre, descripcion, precio, existencias) values ('Cabbage - Red', 'Clothing', 16572, 94);
insert into productos (nombre, descripcion, precio, existencias) values ('Momiji Oroshi Chili Sauce', 'Baby', 9477, 76);
insert into productos (nombre, descripcion, precio, existencias) values ('Apricots - Dried', 'Tools', 9961, 21);
insert into productos (nombre, descripcion, precio, existencias) values ('Chutney Sauce - Mango', 'Music', 16120, 22);
insert into productos (nombre, descripcion, precio, existencias) values ('Gherkin', 'Games', 1599, 92);
insert into productos (nombre, descripcion, precio, existencias) values ('Halibut - Whole, Fresh', 'Electronics', 2618, 10);
insert into productos (nombre, descripcion, precio, existencias) values ('Potatoes - Peeled', 'Tools', 6543, 92);
insert into productos (nombre, descripcion, precio, existencias) values ('Beef - Salted', 'Outdoors', 5338, 31);
